//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group_Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Group_Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat
        ///Dog
        ///Box
        ///Sun
        ///Hat
        ///Pen
        ///Rat
        ///Cup
        ///Lip
        ///Net
        ///Fox
        ///Bus
        ///Map
        ///Bed
        ///Sky
        ///Log
        ///Fan
        ///Joy
        ///Run
        ///Tap
        ///Key
        ///Leg
        ///Air
        ///Bee
        ///Mud
        ///Pot
        ///Kit
        ///Rat
        ///Zip
        ///Jam
        ///Boat
        ///Cake
        ///Duck
        ///Echo
        ///Fire
        ///Gold
        ///Hope
        ///Joke
        ///King
        ///Lamp
        ///Moon
        ///Nail
        ///Oven
        ///Park
        ///Quiz
        ///Rain
        ///Ship
        ///Tree
        ///Unit
        ///Vast
        ///Wolf
        ///Yarn
        ///Zone
        ///Golf
        ///Desk
        ///Leaf
        ///Wave
        ///Rush
        ///Mint
        ///Bath
        ///Apple
        ///Beach
        ///Crane
        ///Dream
        ///Earth
        ///Flake
        ///Grape
        ///House
        ///Juice
        ///Knife
        ///Lemon
        ///Money
        ///Night
        ///Ocean
        ///Peach
        ///Quilt
        ///River
        ///Stone
        ///Tiger
        ///Umbra
        ///Vivid
        ///Whale
        ///Place
        ///Youth
        ///Zebra
        ///Angel
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cat {
            get {
                return ResourceManager.GetString("Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream fellowship {
            get {
                return ResourceManager.GetStream("fellowship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions:
        ///Type the correct word in to make the pickaxe mine the block.
        ///You have 5 lives.
        ///You have a minute to guess as many words as possible.
        ///Press the mine button after you put the word in the text box..
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
    }
}
